### ISSUE TITLE
How to use from_file and to_file?

### ISSUE THREAD

**Issue by Bluscream** [yakubique/json-utils#1]
https://github.com/grayjay-sources/grayjay-sources.github.io/blob/main/.github/workflows/sort_sources.yaml

**Comment by opa-oz** [comment]
Hello @Bluscream!

I apologize for not documenting the parameters. I will fix that shortly here - #2.

In your example:
You don't need to pass the output.

1. Assign an id to your sorting action (for example, `id: sorted_sources`).
2. Retrieve `steps.sorted_source.outputs.result` - this will be the path to the output file (in the /tmp directory).
3. To replace your file, use run: `cp "${{ steps.sorted_sources.outputs.result }}" sources.json`.

So, your steps should look something like this:
```yaml

    - name: Validate and Sort JSON
      uses: yakubique/json-utils@v1.6
      id: sorted_sources
      with:
        action: 'sort'
        type: "nested-json"
        key: "name"
        from_file: 'true'
        to_file: 'true'
        input: 'sources.json'

    - name: Commit and Push Sorted JSON
      run: |
        cp "${{ steps.sorted_sources.outputs.result }}" sources.json
        git add sources.json
        git commit -m "Sort sources.json"
        git push

```

**Comment by opa-oz** [comment]
@Bluscream sorry, I made a typo (thus your action is failing)

```
cp "${{ steps.sorted_sources.outputs.result }} sources.json
```

```
cp "${{ steps.sorted_sources.outputs.result }}" sources.json
----------------------------------------------^
```

**Comment by Bluscream** [comment]
What kind of sorting algorithm does this use so it empties out the json? https://github.com/grayjay-sources/grayjay-sources.github.io/actions/runs/9733873475/job/26861262922#step:5:9

**Comment by opa-oz** [comment]
@Bluscream 
I'm afraid it just output whole JSON as 1 line:
https://github.com/opa-oz/grayjay-sources.github.io/actions/runs/9739678479/job/26875321233

![Screenshot 2024-07-01 at 16 05 01](https://github.com/yakubique/json-utils/assets/34550675/07792c17-043f-469e-aa9f-f57c31b77596)


**UPDATE:**
Added `space` support for you: https://github.com/opa-oz/grayjay-sources.github.io/actions/runs/9740151136/job/26876689391

If you upgrade version of json-utils and add `space` property (number which is amount of spaces in indent):
```yaml
    - name: Validate and Sort JSON
      uses: yakubique/json-utils@v1.7  # <===== new version
      id: sorted_sources
      with:
        action: 'sort'
        type: "nested-json"
        key: "name"
        from_file: 'true'
        to_file: 'true'
        space: 4 # <===== indent
        input: 'sources.json'
```

![Screenshot 2024-07-01 at 16 41 33](https://github.com/yakubique/json-utils/assets/34550675/bd48e107-c77c-4d16-8df8-86cb7603bd53)
